# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log_proto/log.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'log_proto/log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13log_proto/log.proto\x12\x07logging\x1a\x1fgoogle/protobuf/timestamp.proto\"[\n\nLogMessage\x12\r\n\x05level\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x03 \x01(\t\"=\n\x12RecordLogsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0ereceived_count\x18\x02 \x01(\r2R\n\x0eLoggingService\x12@\n\nRecordLogs\x12\x13.logging.LogMessage\x1a\x1b.logging.RecordLogsResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_proto.log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGMESSAGE']._serialized_start=65
  _globals['_LOGMESSAGE']._serialized_end=156
  _globals['_RECORDLOGSRESPONSE']._serialized_start=158
  _globals['_RECORDLOGSRESPONSE']._serialized_end=219
  _globals['_LOGGINGSERVICE']._serialized_start=221
  _globals['_LOGGINGSERVICE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
